import type { Creator, Drop, Experience, HowItWorksStep } from "./types";

export const featuredCreators: Creator[] = [
  {
    id: "c1",
    name: "Aria Voss",
    handle: "@ariavoss",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=aria&backgroundColor=b6e3f4",
    category: "Music",
    rating: 4.97,
    reviewCount: 1240,
    responseTime: "< 2 hrs",
    price: 49,
    isVerified: true,
    isFeatured: true,
  },
  {
    id: "c2",
    name: "Marcus Ren",
    handle: "@marcusren",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus&backgroundColor=ffdfbf",
    category: "Film",
    rating: 4.91,
    reviewCount: 873,
    responseTime: "< 4 hrs",
    price: 75,
    isVerified: true,
    isFeatured: true,
  },
  {
    id: "c3",
    name: "Zola Kim",
    handle: "@zolakim",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=zola&backgroundColor=c0aede",
    category: "Comedy",
    rating: 4.99,
    reviewCount: 3102,
    responseTime: "< 1 hr",
    price: 29,
    isVerified: true,
    isFeatured: false,
  },
];

export const allCreators: Creator[] = [
  ...featuredCreators,
  {
    id: "c4",
    name: "Dex Navarro",
    handle: "@dexnavarro",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=dex&backgroundColor=d1f0d1",
    category: "Sports",
    rating: 4.88,
    reviewCount: 610,
    responseTime: "< 6 hrs",
    price: 60,
    isVerified: true,
  },
  {
    id: "c5",
    name: "Serena Blak",
    handle: "@serenablak",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=serena&backgroundColor=ffd5dc",
    category: "Art",
    rating: 4.95,
    reviewCount: 420,
    responseTime: "< 3 hrs",
    price: 99,
    isVerified: true,
  },
  {
    id: "c6",
    name: "Eli Storm",
    handle: "@elistorm",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=eli&backgroundColor=ffe4b5",
    category: "Tech",
    rating: 4.82,
    reviewCount: 297,
    responseTime: "< 8 hrs",
    price: 120,
    isVerified: false,
  },
];

export const drops: Drop[] = [
  {
    id: "d1",
    title: "Midnight Studio Session NFT",
    description: "A 1-of-1 digital collectible capturing a raw, unfiltered 3AM recording session — stems, stems, and soul.",
    category: "Music",
    image: "https://picsum.photos/seed/drop1/600/400",
    edition: "1 of 1",
    creatorName: "Aria Voss",
    creatorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=aria&backgroundColor=b6e3f4",
    currentBid: 1250,
    buyNowPrice: 3500,
    totalBids: 18,
    endsIn: new Date(Date.now() + 1000 * 60 * 60 * 11 + 1000 * 60 * 34).toISOString(),
  },
  {
    id: "d2",
    title: "Director's Cut — The Final Frame",
    description: "Signed limited-edition print from Marcus's award-winning short, with handwritten director's notes.",
    category: "Film",
    image: "https://picsum.photos/seed/drop2/600/400",
    edition: "3 of 10",
    creatorName: "Marcus Ren",
    creatorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus&backgroundColor=ffdfbf",
    currentBid: 780,
    buyNowPrice: null,
    totalBids: 9,
    endsIn: new Date(Date.now() + 1000 * 60 * 60 * 23 + 1000 * 60 * 7).toISOString(),
  },
  {
    id: "d3",
    title: "The Unaired Pilot — Original Script",
    description: "Zola's never-released comedy pilot script with margin doodles, crossed-out jokes, and real notes from the writer's room.",
    category: "Comedy",
    image: "https://picsum.photos/seed/drop3/600/400",
    edition: "1 of 1",
    creatorName: "Zola Kim",
    creatorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=zola&backgroundColor=c0aede",
    currentBid: 440,
    buyNowPrice: 900,
    totalBids: 31,
    endsIn: new Date(Date.now() + 1000 * 60 * 60 * 6 + 1000 * 60 * 22).toISOString(),
  },
];

export const experiences: Experience[] = [
  {
    id: "e1",
    creatorId: "c1",
    creatorName: "Aria Voss",
    creatorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=aria&backgroundColor=b6e3f4",
    title: "Private Studio Listening Party",
    description: "Join Aria in her LA studio for an exclusive first listen of her upcoming album, Q&A, and dinner for 6.",
    image: "https://picsum.photos/seed/exp1/600/400",
    location: "Los Angeles, CA",
    date: "Aug 14, 2025",
    duration: "3 hours",
    capacity: 6,
    spotsLeft: 2,
    pricingMode: "both",
    buyNowPrice: 599,
    currentBid: 320,
    endsIn: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    category: "Music",
    tags: ["Exclusive", "Dinner Included", "Q&A"],
  },
  {
    id: "e2",
    creatorId: "c2",
    creatorName: "Marcus Ren",
    creatorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus&backgroundColor=ffdfbf",
    title: "On-Set Shadow Day",
    description: "Spend a full day on Marcus's active film set. Watch scenes being shot, sit in on editing, and get a personal walkthrough.",
    image: "https://picsum.photos/seed/exp2/600/400",
    location: "New York, NY",
    date: "Sep 3, 2025",
    duration: "Full Day",
    capacity: 1,
    spotsLeft: 1,
    pricingMode: "buyNow",
    buyNowPrice: 1200,
    currentBid: null,
    endsIn: null,
    category: "Film",
    tags: ["1-on-1", "Behind the Scenes", "Pro Mentorship"],
  },
  {
    id: "e3",
    creatorId: "c3",
    creatorName: "Zola Kim",
    creatorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=zola&backgroundColor=c0aede",
    title: "Comedy Writing Workshop",
    description: "A 2-hour live Zoom workshop with Zola — pitch jokes, get roasted (gently), and leave with a tighter set.",
    image: "https://picsum.photos/seed/exp3/600/400",
    location: "Online",
    date: "Jul 28, 2025",
    duration: "2 hours",
    capacity: 12,
    spotsLeft: 7,
    pricingMode: "auction",
    buyNowPrice: null,
    currentBid: 85,
    endsIn: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    category: "Comedy",
    tags: ["Online", "Interactive", "Limited Seats"],
  },
];

export const howItWorksSteps: HowItWorksStep[] = [
  {
    id: "h1",
    step: 1,
    title: "Browse Creators",
    description: "Explore verified creators across music, film, comedy, sports, and more. Filter by category, price, or response time.",
    icon: "🔍",
  },
  {
    id: "h2",
    step: 2,
    title: "Request or Bid",
    description: "Send a personalised video request, place a bid on a Drop, or buy your Experience spot instantly.",
    icon: "⚡",
  },
  {
    id: "h3",
    step: 3,
    title: "Creator Delivers",
    description: "Your creator records a custom message, ships a collectible, or welcomes you to an exclusive Experience.",
    icon: "🎬",
  },
  {
    id: "h4",
    step: 4,
    title: "Cherish Forever",
    description: "Download, share, or display your piece. Every moment is exclusive, every connection is real.",
    icon: "✨",
  },
];

export function getCreatorById(id: string) {
  return allCreators.find((c) => c.id === id);
}